version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"     # RabbitMQ standard port
      - "15672:15672"   # RabbitMQ management UI port
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq   # Volume for persistent data storage